#!/bin/bash

ARGS="${ARGS} -v /etc/group:/etc/group:ro"
ARGS="${ARGS} -v /etc/passwd:/etc/passwd:ro"
ARGS="${ARGS} -v /etc/hostname:/etc/hostname:ro"
ARGS="${ARGS} --network host "
ARGS="${ARGS} -v /etc/resolv.conf:/etc/resolv.conf:ro "
ARGS="${ARGS} -v $HOME/:$HOME/"
ARGS="${ARGS} -u $(id -u ${USER}):$(id -g ${USER})"
ARGS="${ARGS} -h $(hostname)-docker"
[[ -d /synopsys ]] && ARGS="${ARGS} -v /synopsys/:/synopsys/:ro"
[[ -d /scratch ]] && ARGS="${ARGS} -v /scratch/:/scratch"
for i in utils mentor synopsys cadence
do
    [[ -f /opt/utils/${i}rc ]] && ARGS="${ARGS} -v /opt/${i}rc:/opt/${i}rc:ro"
done
[[ -n "$DV_SIMULATORS" ]] && ARGS="${ARGS} -e DV_SIMULATORS=$DV_SIMULATORS"

current_path=$(pwd)

docker run --rm ${ARGS} -it openhw/debian10/cva6 bash -c "cd $current_path; source /opt/utils/utilsrc; $*;"
